# Generated by Django 4.2.3 on 2023-07-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='banco',
            field=models.CharField(choices=[('NU', 'Nubank'), ('CE', 'Caixa Econômica'), ('C6', 'C6 Bank'), ('SA', 'Santander'), ('IT', 'Itaú')], max_length=3),
        ),
    ]
